server:
  port: 10010
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://userservice
          predicates:
            - Path=/user/**
        - id: diet-service
          uri: lb://dietservice
          predicates:
            - Path=/diet/**
        - id: disease-service
          uri: lb://diseaseservice
          predicates:
            - Path=/disease/**
        - id: health-service
          uri: lb://healthservice
          predicates:
            - Path=/health/**