spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/health_project_data
      username: root
      password: lzn123

  mail:
    protocol: smtps
    #protocol: smtp
    # 配置 SMTP 服务器地址
    host: smtp.163.com
    # 发送者邮箱
    username: lzn_11011@163.com
    #username: 482087021@qq.com
    # 配置密码，注意不是真正的密码，而是刚刚申请到的授权码
    password: WINNFGHCHFRZEBVR
    # 端口号465或587
    port: 465
    #port: 587
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8


server:
  port: 8061

mybatis-plus:
  
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
dietservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
diseaseservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则
ribbon:
  eager-load:
    enabled: true
    clients:
      - userservice
feign:
  client:
    config:
      -disease:
        logger-level: basic
      -diet:
        logger-level: basic
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50